version: '3.7'
services:
    db:
        image: 'kartoza/postgis:14-3.2'
        container_name: sabonah.db
        ports:
            - DOCKER_POSTGRES_PORT:5432
        environment:
            - POSTGRES_USER=DOCKER_POSTGRES_USER
            - POSTGRES_PASS=DOCKER_POSTGRES_PASS
            - POSTGRES_DB=DOCKER_POSTGRES_DB
        volumes:
            - 'sabonah_postgres_data:/var/lib/postgresql'

    redis:
        container_name: sabonah.redis
        image: 'bitnami/redis:6.0.16'
        ports:
            - DOCKER_REDIS_PORT:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - 'sabonah_redis_data:/bitnami'
backend:
  build: .

  container_name: mybackend

  ports:
    - "3002:3002"

  environment:
    DATABASE_URL: postgres://postgres:click123@db:5432/postgres_db_fyp
    REDIS_URL: redis://redis:6379

  depends_on:
    - db
    - redis
volumes:
    sabonah_postgres_data:
        external: true
    sabonah_redis_data:
        external: true
